# Site settings
title: JUG Essen
email: team@jug-essen.de
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

# Permanent Links
permalink: /blog/:year/:month/:day/:title

# Pagination
paginate: 5
gems: [jekyll-paginate]
paginate_path: "/blog/page:num/"

# Google analytics
google_analytics_code: UA-77735068-1

# social sharing
twitter_username: JUG_Essen
meetup_username: JUG-Essen
github_username: jug-essen
# Kommentarfunktion / Disqus
disqus_username: jugessen
disqus_domain: http://www.jug-essen.de
sitemap_url: http://www.jug-essen.de

# Collections
collections:
  locations:
    output: true
    permalink: /locations/:path/
  authors:
    output: true
    permalink: /authors/:path/
  sponsors:
    output: true
    permalink: /sponsors/:path/
  events:
    output: true
    permalink: /events/:path/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "sponsors"
    values:
      layout: "sponsor"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author_profile"
